-- Expand countries table with comprehensive list of countries
-- This migration adds many more countries to the database for better coverage

-- Use INSERT ... ON CONFLICT DO NOTHING to avoid duplicates
INSERT INTO countries (code, name, region, subregion, capital, population, government_type, watchlist) VALUES
-- Europe (additional)
    ('NL', 'Netherlands', 'Europe', 'Western Europe', 'Amsterdam', 17500000, 'Unitary parliamentary constitutional monarchy', false),
    ('BE', 'Belgium', 'Europe', 'Western Europe', 'Brussels', 11600000, 'Federal parliamentary constitutional monarchy', false),
    ('CH', 'Switzerland', 'Europe', 'Western Europe', 'Bern', 8700000, 'Federal assembly-independent directorial republic', false),
    ('AT', 'Austria', 'Europe', 'Western Europe', 'Vienna', 9000000, 'Federal parliamentary republic', false),
    ('SE', 'Sweden', 'Europe', 'Northern Europe', 'Stockholm', 10400000, 'Unitary parliamentary constitutional monarchy', false),
    ('NO', 'Norway', 'Europe', 'Northern Europe', 'Oslo', 5400000, 'Unitary parliamentary constitutional monarchy', false),
    ('DK', 'Denmark', 'Europe', 'Northern Europe', 'Copenhagen', 5800000, 'Unitary parliamentary constitutional monarchy', false),
    ('FI', 'Finland', 'Europe', 'Northern Europe', 'Helsinki', 5500000, 'Unitary parliamentary republic', false),
    ('GR', 'Greece', 'Europe', 'Southern Europe', 'Athens', 10700000, 'Unitary parliamentary republic', false),
    ('PT', 'Portugal', 'Europe', 'Southern Europe', 'Lisbon', 10300000, 'Unitary semi-presidential republic', false),
    ('ES', 'Spain', 'Europe', 'Southern Europe', 'Madrid', 47000000, 'Unitary parliamentary constitutional monarchy', false),
    ('IE', 'Ireland', 'Europe', 'Northern Europe', 'Dublin', 5000000, 'Unitary parliamentary republic', false),
    ('CZ', 'Czech Republic', 'Europe', 'Central Europe', 'Prague', 10700000, 'Unitary parliamentary republic', false),
    ('HU', 'Hungary', 'Europe', 'Central Europe', 'Budapest', 9700000, 'Unitary parliamentary republic', false),
    ('RO', 'Romania', 'Europe', 'Eastern Europe', 'Bucharest', 19200000, 'Unitary semi-presidential republic', false),
    ('BG', 'Bulgaria', 'Europe', 'Eastern Europe', 'Sofia', 6900000, 'Unitary parliamentary republic', false),
    ('RS', 'Serbia', 'Europe', 'Southern Europe', 'Belgrade', 8700000, 'Unitary parliamentary republic', false),
    ('HR', 'Croatia', 'Europe', 'Southern Europe', 'Zagreb', 3900000, 'Unitary parliamentary republic', false),
    ('SK', 'Slovakia', 'Europe', 'Central Europe', 'Bratislava', 5500000, 'Unitary parliamentary republic', false),
    ('SI', 'Slovenia', 'Europe', 'Southern Europe', 'Ljubljana', 2100000, 'Unitary parliamentary republic', false),
    ('LT', 'Lithuania', 'Europe', 'Northern Europe', 'Vilnius', 2800000, 'Unitary semi-presidential republic', false),
    ('LV', 'Latvia', 'Europe', 'Northern Europe', 'Riga', 1900000, 'Unitary parliamentary republic', false),
    ('EE', 'Estonia', 'Europe', 'Northern Europe', 'Tallinn', 1300000, 'Unitary parliamentary republic', false),
    ('BY', 'Belarus', 'Europe', 'Eastern Europe', 'Minsk', 9400000, 'Unitary presidential republic', true),
    ('MD', 'Moldova', 'Europe', 'Eastern Europe', 'Chișinău', 2600000, 'Unitary parliamentary republic', false),
    ('GE', 'Georgia', 'Asia', 'Western Asia', 'Tbilisi', 3700000, 'Unitary semi-presidential republic', false),
    ('AM', 'Armenia', 'Asia', 'Western Asia', 'Yerevan', 3000000, 'Unitary parliamentary republic', false),
    ('AZ', 'Azerbaijan', 'Asia', 'Western Asia', 'Baku', 10100000, 'Unitary semi-presidential republic', false),
    ('KZ', 'Kazakhstan', 'Asia', 'Central Asia', 'Nur-Sultan', 19000000, 'Unitary presidential republic', false),
    ('UZ', 'Uzbekistan', 'Asia', 'Central Asia', 'Tashkent', 34000000, 'Unitary presidential republic', false),
    ('AL', 'Albania', 'Europe', 'Southern Europe', 'Tirana', 2800000, 'Unitary parliamentary republic', false),
    ('BA', 'Bosnia and Herzegovina', 'Europe', 'Southern Europe', 'Sarajevo', 3300000, 'Federal parliamentary republic', false),
    ('MK', 'North Macedonia', 'Europe', 'Southern Europe', 'Skopje', 2100000, 'Unitary parliamentary republic', false),
    ('ME', 'Montenegro', 'Europe', 'Southern Europe', 'Podgorica', 620000, 'Unitary parliamentary republic', false),
    ('AD', 'Andorra', 'Europe', 'Southern Europe', 'Andorra la Vella', 77000, 'Unitary parliamentary constitutional diarchy', false),
    ('SM', 'San Marino', 'Europe', 'Southern Europe', 'San Marino', 34000, 'Unitary parliamentary republic', false),
    ('MC', 'Monaco', 'Europe', 'Western Europe', 'Monaco', 39000, 'Unitary parliamentary constitutional monarchy', false),
    ('LI', 'Liechtenstein', 'Europe', 'Western Europe', 'Vaduz', 38000, 'Unitary parliamentary constitutional monarchy', false),
    ('VA', 'Vatican City', 'Europe', 'Southern Europe', 'Vatican City', 825, 'Unitary absolute elective monarchy', false),

-- Americas (additional)
    ('AR', 'Argentina', 'Americas', 'South America', 'Buenos Aires', 45100000, 'Federal presidential republic', false),
    ('CL', 'Chile', 'Americas', 'South America', 'Santiago', 19100000, 'Unitary presidential republic', false),
    ('CO', 'Colombia', 'Americas', 'South America', 'Bogotá', 50800000, 'Unitary presidential republic', false),
    ('PE', 'Peru', 'Americas', 'South America', 'Lima', 33000000, 'Unitary presidential republic', false),
    ('EC', 'Ecuador', 'Americas', 'South America', 'Quito', 17600000, 'Unitary presidential republic', false),
    ('BO', 'Bolivia', 'Americas', 'South America', 'Sucre', 11600000, 'Unitary presidential republic', false),
    ('PY', 'Paraguay', 'Americas', 'South America', 'Asunción', 7200000, 'Unitary presidential republic', false),
    ('UY', 'Uruguay', 'Americas', 'South America', 'Montevideo', 3500000, 'Unitary presidential republic', false),
    ('CR', 'Costa Rica', 'Americas', 'Central America', 'San José', 5100000, 'Unitary presidential republic', false),
    ('PA', 'Panama', 'Americas', 'Central America', 'Panama City', 4300000, 'Unitary presidential republic', false),
    ('GT', 'Guatemala', 'Americas', 'Central America', 'Guatemala City', 17900000, 'Unitary presidential republic', false),
    ('HN', 'Honduras', 'Americas', 'Central America', 'Tegucigalpa', 9900000, 'Unitary presidential republic', false),
    ('NI', 'Nicaragua', 'Americas', 'Central America', 'Managua', 6600000, 'Unitary presidential republic', false),
    ('SV', 'El Salvador', 'Americas', 'Central America', 'San Salvador', 6500000, 'Unitary presidential republic', false),
    ('CU', 'Cuba', 'Americas', 'Caribbean', 'Havana', 11300000, 'Unitary Marxist-Leninist one-party socialist republic', false),
    ('DO', 'Dominican Republic', 'Americas', 'Caribbean', 'Santo Domingo', 10900000, 'Unitary presidential republic', false),
    ('JM', 'Jamaica', 'Americas', 'Caribbean', 'Kingston', 3000000, 'Unitary parliamentary constitutional monarchy', false),
    ('HT', 'Haiti', 'Americas', 'Caribbean', 'Port-au-Prince', 11400000, 'Unitary semi-presidential republic', false),
    ('TT', 'Trinidad and Tobago', 'Americas', 'Caribbean', 'Port of Spain', 1400000, 'Unitary parliamentary republic', false),
    ('BB', 'Barbados', 'Americas', 'Caribbean', 'Bridgetown', 290000, 'Unitary parliamentary constitutional monarchy', false),
    ('BS', 'Bahamas', 'Americas', 'Caribbean', 'Nassau', 390000, 'Unitary parliamentary constitutional monarchy', false),
    ('GY', 'Guyana', 'Americas', 'South America', 'Georgetown', 790000, 'Unitary presidential republic', false),
    ('SR', 'Suriname', 'Americas', 'South America', 'Paramaribo', 590000, 'Unitary presidential republic', false),
    ('GF', 'French Guiana', 'Americas', 'South America', 'Cayenne', 290000, 'Overseas department', false),

-- Asia (additional)
    ('TH', 'Thailand', 'Asia', 'Southeast Asia', 'Bangkok', 70000000, 'Unitary parliamentary constitutional monarchy', false),
    ('VN', 'Vietnam', 'Asia', 'Southeast Asia', 'Hanoi', 97300000, 'Unitary Marxist-Leninist one-party socialist republic', false),
    ('MY', 'Malaysia', 'Asia', 'Southeast Asia', 'Kuala Lumpur', 32700000, 'Federal parliamentary constitutional monarchy', false),
    ('SG', 'Singapore', 'Asia', 'Southeast Asia', 'Singapore', 5700000, 'Unitary parliamentary republic', false),
    ('PH', 'Philippines', 'Asia', 'Southeast Asia', 'Manila', 110800000, 'Unitary presidential republic', false),
    ('MM', 'Myanmar', 'Asia', 'Southeast Asia', 'Naypyidaw', 54400000, 'Unitary parliamentary republic', false),
    ('KH', 'Cambodia', 'Asia', 'Southeast Asia', 'Phnom Penh', 16700000, 'Unitary parliamentary constitutional monarchy', false),
    ('LA', 'Laos', 'Asia', 'Southeast Asia', 'Vientiane', 7300000, 'Unitary Marxist-Leninist one-party socialist republic', false),
    ('BN', 'Brunei', 'Asia', 'Southeast Asia', 'Bandar Seri Begawan', 440000, 'Unitary Islamic absolute monarchy', false),
    ('BD', 'Bangladesh', 'Asia', 'South Asia', 'Dhaka', 164700000, 'Unitary parliamentary republic', false),
    ('LK', 'Sri Lanka', 'Asia', 'South Asia', 'Colombo', 22000000, 'Unitary semi-presidential republic', false),
    ('NP', 'Nepal', 'Asia', 'South Asia', 'Kathmandu', 29100000, 'Federal parliamentary republic', false),
    ('BT', 'Bhutan', 'Asia', 'South Asia', 'Thimphu', 770000, 'Unitary parliamentary constitutional monarchy', false),
    ('MV', 'Maldives', 'Asia', 'South Asia', 'Malé', 540000, 'Unitary presidential republic', false),
    ('MN', 'Mongolia', 'Asia', 'East Asia', 'Ulaanbaatar', 3300000, 'Unitary semi-presidential republic', false),
    ('HK', 'Hong Kong', 'Asia', 'East Asia', 'Hong Kong', 7500000, 'Special administrative region', true),
    ('AE', 'United Arab Emirates', 'Asia', 'Western Asia', 'Abu Dhabi', 10000000, 'Federal absolute monarchy', false),
    ('IQ', 'Iraq', 'Asia', 'Western Asia', 'Baghdad', 40200000, 'Federal parliamentary republic', true),
    ('JO', 'Jordan', 'Asia', 'Western Asia', 'Amman', 11000000, 'Unitary parliamentary constitutional monarchy', false),
    ('LB', 'Lebanon', 'Asia', 'Western Asia', 'Beirut', 6800000, 'Unitary parliamentary republic', false),
    ('KW', 'Kuwait', 'Asia', 'Western Asia', 'Kuwait City', 4300000, 'Unitary constitutional monarchy', false),
    ('OM', 'Oman', 'Asia', 'Western Asia', 'Muscat', 5100000, 'Unitary absolute monarchy', false),
    ('QA', 'Qatar', 'Asia', 'Western Asia', 'Doha', 2900000, 'Unitary absolute monarchy', false),
    ('BH', 'Bahrain', 'Asia', 'Western Asia', 'Manama', 1700000, 'Unitary constitutional monarchy', false),
    ('TJ', 'Tajikistan', 'Asia', 'Central Asia', 'Dushanbe', 9500000, 'Unitary presidential republic', false),
    ('TM', 'Turkmenistan', 'Asia', 'Central Asia', 'Ashgabat', 6000000, 'Unitary presidential republic', false),
    ('KG', 'Kyrgyzstan', 'Asia', 'Central Asia', 'Bishkek', 6500000, 'Unitary parliamentary republic', false),

-- Africa (additional)
    ('KE', 'Kenya', 'Africa', 'Eastern Africa', 'Nairobi', 53700000, 'Unitary presidential republic', false),
    ('ET', 'Ethiopia', 'Africa', 'Eastern Africa', 'Addis Ababa', 115000000, 'Federal parliamentary republic', false),
    ('TZ', 'Tanzania', 'Africa', 'Eastern Africa', 'Dodoma', 59700000, 'Unitary presidential republic', false),
    ('UG', 'Uganda', 'Africa', 'Eastern Africa', 'Kampala', 45800000, 'Unitary presidential republic', false),
    ('RW', 'Rwanda', 'Africa', 'Eastern Africa', 'Kigali', 13000000, 'Unitary presidential republic', false),
    ('GH', 'Ghana', 'Africa', 'Western Africa', 'Accra', 31000000, 'Unitary presidential republic', false),
    ('SN', 'Senegal', 'Africa', 'Western Africa', 'Dakar', 16700000, 'Unitary presidential republic', false),
    ('CI', 'Ivory Coast', 'Africa', 'Western Africa', 'Yamoussoukro', 26300000, 'Unitary presidential republic', false),
    ('ML', 'Mali', 'Africa', 'Western Africa', 'Bamako', 20200000, 'Unitary semi-presidential republic', false),
    ('BF', 'Burkina Faso', 'Africa', 'Western Africa', 'Ouagadougou', 20900000, 'Unitary semi-presidential republic', false),
    ('NE', 'Niger', 'Africa', 'Western Africa', 'Niamey', 24200000, 'Unitary semi-presidential republic', false),
    ('TD', 'Chad', 'Africa', 'Middle Africa', 'N''Djamena', 16400000, 'Unitary presidential republic', false),
    ('CM', 'Cameroon', 'Africa', 'Middle Africa', 'Yaoundé', 26500000, 'Unitary presidential republic', false),
    ('CD', 'DR Congo', 'Africa', 'Middle Africa', 'Kinshasa', 89000000, 'Unitary semi-presidential republic', false),
    ('CG', 'Congo', 'Africa', 'Middle Africa', 'Brazzaville', 5500000, 'Unitary semi-presidential republic', false),
    ('AO', 'Angola', 'Africa', 'Middle Africa', 'Luanda', 32800000, 'Unitary presidential republic', false),
    ('ZM', 'Zambia', 'Africa', 'Eastern Africa', 'Lusaka', 18300000, 'Unitary presidential republic', false),
    ('ZW', 'Zimbabwe', 'Africa', 'Eastern Africa', 'Harare', 15000000, 'Unitary presidential republic', false),
    ('MW', 'Malawi', 'Africa', 'Eastern Africa', 'Lilongwe', 19100000, 'Unitary presidential republic', false),
    ('MZ', 'Mozambique', 'Africa', 'Eastern Africa', 'Maputo', 31200000, 'Unitary presidential republic', false),
    ('MG', 'Madagascar', 'Africa', 'Eastern Africa', 'Antananarivo', 27700000, 'Unitary semi-presidential republic', false),
    ('MA', 'Morocco', 'Africa', 'Northern Africa', 'Rabat', 37000000, 'Unitary parliamentary constitutional monarchy', false),
    ('DZ', 'Algeria', 'Africa', 'Northern Africa', 'Algiers', 43800000, 'Unitary semi-presidential republic', false),
    ('TN', 'Tunisia', 'Africa', 'Northern Africa', 'Tunis', 11900000, 'Unitary semi-presidential republic', false),
    ('LY', 'Libya', 'Africa', 'Northern Africa', 'Tripoli', 6900000, 'Unitary provisional government', false),
    ('SD', 'Sudan', 'Africa', 'Northern Africa', 'Khartoum', 43800000, 'Federal provisional government', true),
    ('SS', 'South Sudan', 'Africa', 'Eastern Africa', 'Juba', 11200000, 'Federal presidential republic', false),
    ('ER', 'Eritrea', 'Africa', 'Eastern Africa', 'Asmara', 3500000, 'Unitary one-party presidential republic', false),
    ('SO', 'Somalia', 'Africa', 'Eastern Africa', 'Mogadishu', 15800000, 'Federal parliamentary republic', false),
    ('DJ', 'Djibouti', 'Africa', 'Eastern Africa', 'Djibouti', 990000, 'Unitary semi-presidential republic', false),
    ('BW', 'Botswana', 'Africa', 'Southern Africa', 'Gaborone', 2350000, 'Unitary parliamentary republic', false),
    ('NA', 'Namibia', 'Africa', 'Southern Africa', 'Windhoek', 2540000, 'Unitary semi-presidential republic', false),
    ('LS', 'Lesotho', 'Africa', 'Southern Africa', 'Maseru', 2100000, 'Unitary parliamentary constitutional monarchy', false),
    ('SZ', 'Eswatini', 'Africa', 'Southern Africa', 'Mbabane', 1200000, 'Unitary absolute monarchy', false),
    ('MU', 'Mauritius', 'Africa', 'Eastern Africa', 'Port Louis', 1300000, 'Unitary parliamentary republic', false),
    ('SC', 'Seychelles', 'Africa', 'Eastern Africa', 'Victoria', 98000, 'Unitary presidential republic', false),
    ('KM', 'Comoros', 'Africa', 'Eastern Africa', 'Moroni', 870000, 'Federal presidential republic', false),
    ('CV', 'Cape Verde', 'Africa', 'Western Africa', 'Praia', 560000, 'Unitary semi-presidential republic', false),
    ('GW', 'Guinea-Bissau', 'Africa', 'Western Africa', 'Bissau', 1960000, 'Unitary semi-presidential republic', false),
    ('GN', 'Guinea', 'Africa', 'Western Africa', 'Conakry', 13100000, 'Unitary presidential republic', false),
    ('SL', 'Sierra Leone', 'Africa', 'Western Africa', 'Freetown', 8000000, 'Unitary presidential republic', false),
    ('LR', 'Liberia', 'Africa', 'Western Africa', 'Monrovia', 5100000, 'Unitary presidential republic', false),
    ('TG', 'Togo', 'Africa', 'Western Africa', 'Lomé', 8300000, 'Unitary presidential republic', false),
    ('BJ', 'Benin', 'Africa', 'Western Africa', 'Porto-Novo', 12100000, 'Unitary presidential republic', false),
    ('MR', 'Mauritania', 'Africa', 'Western Africa', 'Nouakchott', 4650000, 'Unitary semi-presidential republic', false),
    ('GA', 'Gabon', 'Africa', 'Middle Africa', 'Libreville', 2200000, 'Unitary presidential republic', false),
    ('GQ', 'Equatorial Guinea', 'Africa', 'Middle Africa', 'Malabo', 1400000, 'Unitary presidential republic', false),
    ('ST', 'São Tomé and Príncipe', 'Africa', 'Middle Africa', 'São Tomé', 220000, 'Unitary semi-presidential republic', false),
    ('CF', 'Central African Republic', 'Africa', 'Middle Africa', 'Bangui', 4800000, 'Unitary presidential republic', false),
    ('BI', 'Burundi', 'Africa', 'Eastern Africa', 'Gitega', 11900000, 'Unitary presidential republic', false),

-- Oceania (additional)
    ('NZ', 'New Zealand', 'Oceania', 'Australia and New Zealand', 'Wellington', 5100000, 'Unitary parliamentary constitutional monarchy', false),
    ('PG', 'Papua New Guinea', 'Oceania', 'Melanesia', 'Port Moresby', 9000000, 'Unitary parliamentary constitutional monarchy', false),
    ('FJ', 'Fiji', 'Oceania', 'Melanesia', 'Suva', 900000, 'Unitary parliamentary republic', false),
    ('NC', 'New Caledonia', 'Oceania', 'Melanesia', 'Nouméa', 290000, 'Special collectivity', false),
    ('VU', 'Vanuatu', 'Oceania', 'Melanesia', 'Port Vila', 310000, 'Unitary parliamentary republic', false),
    ('SB', 'Solomon Islands', 'Oceania', 'Melanesia', 'Honiara', 690000, 'Unitary parliamentary constitutional monarchy', false),
    ('WS', 'Samoa', 'Oceania', 'Polynesia', 'Apia', 200000, 'Unitary parliamentary republic', false),
    ('TO', 'Tonga', 'Oceania', 'Polynesia', 'Nuku''alofa', 100000, 'Unitary parliamentary constitutional monarchy', false),
    ('KI', 'Kiribati', 'Oceania', 'Micronesia', 'Tarawa', 120000, 'Unitary parliamentary republic', false),
    ('MH', 'Marshall Islands', 'Oceania', 'Micronesia', 'Majuro', 59000, 'Unitary parliamentary republic', false),
    ('FM', 'Micronesia', 'Oceania', 'Micronesia', 'Palikir', 110000, 'Federal parliamentary republic', false),
    ('PW', 'Palau', 'Oceania', 'Micronesia', 'Ngerulmud', 18000, 'Unitary presidential republic', false),

-- Additional important countries
    ('IS', 'Iceland', 'Europe', 'Northern Europe', 'Reykjavik', 370000, 'Unitary parliamentary republic', false),
    ('LU', 'Luxembourg', 'Europe', 'Western Europe', 'Luxembourg', 630000, 'Unitary parliamentary constitutional monarchy', false),
    ('MT', 'Malta', 'Europe', 'Southern Europe', 'Valletta', 520000, 'Unitary parliamentary republic', false),
    ('CY', 'Cyprus', 'Asia', 'Western Asia', 'Nicosia', 1200000, 'Unitary presidential republic', false),
    ('XK', 'Kosovo', 'Europe', 'Southern Europe', 'Pristina', 1900000, 'Unitary parliamentary republic', false),
    ('PS', 'Palestine', 'Asia', 'Western Asia', 'Ramallah', 5100000, 'Unitary semi-presidential republic', true)
ON CONFLICT (code) DO UPDATE SET
    name = EXCLUDED.name,
    region = EXCLUDED.region,
    subregion = EXCLUDED.subregion,
    capital = EXCLUDED.capital,
    population = EXCLUDED.population,
    government_type = EXCLUDED.government_type,
    updated_at = NOW();

-- Add comment
COMMENT ON TABLE countries IS 'Comprehensive list of countries worldwide for geopolitical intelligence analysis';
